Repository percona/percona-backup-mongodb, pull requests merged in 2024-03, with the labels that each got.

#917 upgrade to go 1.22
  .github/workflows/ci.yml
  .github/workflows/reviewdog.yml
  docker/Dockerfile
  docker/Dockerfile.k8s
  go.mod
  go.sum
  packaging/scripts/mongodb-backup_builder.sh
Labels: maintenance

#920 fix e2e-tests dockerfiles for Go 1.22
  e2e-tests/docker/pbm.dockerfile
  e2e-tests/docker/tests.dockerfile
Labels: tests

#923 PBM_tests. Add delay for PITR, Return OL8 as base image
  e2e-tests/docker/pbm.dockerfile
  e2e-tests/docker/tests.dockerfile
  e2e-tests/pkg/pbm/clock_skew.go
  e2e-tests/pkg/tests/sharded/trx.go
Labels: maintenance, tests

#921 [linter] remove deprecated rand.Seed() calls
  cmd/pbm-speed-test/main.go
  e2e-tests/cmd/pbm-test/main.go
  e2e-tests/cmd/pbm-test/run.go
  e2e-tests/cmd/pbm-test/run_physical.go
  e2e-tests/pkg/tests/sharded/backuper.go
  e2e-tests/pkg/tests/sharded/test_bounds_check.go
  e2e-tests/pkg/tests/sharded/test_incremental_backup.go
  e2e-tests/pkg/tests/sharded/test_oplog_replay.go
  e2e-tests/pkg/tests/sharded/test_pitr_basic.go
  pbm/restore/physical.go
Labels: maintenance

#919 Fix help for list-file option in Backup command
  cmd/pbm/main.go
Labels: bugfix

#913 skip heavy tests for draft
  .github/workflows/ci.yml
Labels: maintenance, tests

#911 PBM-1159: Make ReadConcern Majority optional
  cmd/pbm-agent/agent.go
  cmd/pbm-agent/main.go
  cmd/pbm-speed-test/main.go
  cmd/pbm/main.go
  cmd/pbm/status.go
  e2e-tests/cmd/ensure-oplog/main.go
  e2e-tests/pkg/pbm/mongo_pbm.go
  e2e-tests/pkg/pbm/mongod.go
  e2e-tests/pkg/tests/state.go
  pbm/backup/logical.go
  pbm/connect/connect.go
  sdk/sdk.go
Labels: feature

#927 [PBM-1252] keep list of physical files in storage
  cmd/pbm-agent/agent.go
  cmd/pbm-agent/backup.go
  cmd/pbm/backup.go
  cmd/pbm/main.go
  pbm/backup/backup.go
  pbm/backup/physical.go
  pbm/backup/query.go
  pbm/backup/storage.go
  pbm/backup/types.go
  pbm/ctrl/cmd.go
  pbm/restore/physical.go
  pbm/storage/azure/azure.go
  pbm/storage/s3/download.go
  pbm/storage/s3/s3.go
  pbm/storage/storage.go
  pbm/version/version.go
  pbm/version/version_test.go
  sdk/impl.go
  sdk/sdk.go
Labels: improvement, bugfix

#929 [PBM-1265] fix for "Cannot execute a write operation in read-only mode"
  pbm/restore/physical.go
Labels: bugfix
