Repository percona/percona-backup-mongodb, pull requests merged in 2024-09, with the labels that each got.

#1005 PBM-1338: Restore Start/Finish time for `describe-restore` command
  cmd/pbm/main.go
  cmd/pbm/restore.go
Labels: bugfix

#1003 [PBM-1312] allow to control max number of parallel collections
  cmd/pbm-agent/agent.go
  cmd/pbm-agent/backup.go
  cmd/pbm-agent/main.go
  cmd/pbm-agent/oplog.go
  cmd/pbm-agent/restore.go
  cmd/pbm/backup.go
  cmd/pbm/main.go
  cmd/pbm/restore.go
  pbm/archive/archive.go
  pbm/backup/backup.go
  pbm/backup/logical.go
  pbm/ctrl/cmd.go
  pbm/restore/logical.go
  pbm/snapshot/backup.go
  pbm/snapshot/dump.go
  pbm/snapshot/restore.go
Labels: feature

#1008 [PBM-1356] ensure capped collection
  cmd/pbm-agent/agent.go
  cmd/pbm-agent/main.go
Labels: bugfix

#1009 PBM-1369: Fix never ending backup after agent is lost
  pbm/backup/backup.go
Labels: bugfix

#1014 PBM-823: enable leftover files check for cancelled backup
  e2e-tests/pkg/tests/sharded/test_backup_cancellation.go
Labels: tests

#949 Use RemoteCredsProvider from aws default stack
  pbm/storage/s3/s3.go
Labels: community, improvement

#1016 PBM-1229: skip waitForStatus on the backup leader
  pbm/backup/backup.go
  pbm/backup/logical.go
  pbm/backup/physical.go
Labels: bugfix

#1022 PBM-886: sync channel set/unset/close ops
  pbm/oplog/backup.go
  pbm/storage/storage.go
Labels: bugfix

#1024 PBM-921: ensure system.views before "creating" views/timeseries
  pbm/oplog/restore.go
Labels: bugfix
