Repository percona/percona-backup-mongodb, pull requests merged in 2024-02, with the labels that each got.

#902 [PBM-907] slice oplog during logical backup
  .github/workflows/reviewdog.yml
  cmd/pbm-agent/agent.go
  cmd/pbm-agent/backup.go
  cmd/pbm-agent/delete.go
  cmd/pbm-agent/oplog.go
  cmd/pbm-agent/restore.go
  cmd/pbm/status.go
  e2e-tests/cmd/ensure-oplog/main.go
  e2e-tests/pkg/tests/sharded/test_delete_backup.go
  e2e-tests/pkg/tests/sharded/test_pitr_basic.go
  internal/backup/backup.go
  internal/backup/chunk.go
  internal/backup/logical.go
  internal/backup/physical.go
  internal/backup/slicer.go
  internal/backup/storage.go
  internal/compress/compress.go
  internal/config/config.go
  internal/ctrl/cmd.go
  internal/ctrl/send.go
  internal/lock/lock.go
  internal/oplog/backup.go
  internal/oplog/chunk.go
  internal/oplog/restore.go
  internal/restore/logical.go
  internal/resync/rsync.go
  internal/slicer/slicer.go
  internal/snapshot/backup.go
  internal/snapshot/dump.go
  internal/storage/fs/fs.go
  internal/topo/cluster.go
  internal/version/version.go
  sdk/sdk.go
Labels: improvement, feature

#905 [PBM-1234, PBM-1236] Unable to delete incremental backups
  cmd/pbm-agent/agent.go
  cmd/pbm-agent/backup.go
  cmd/pbm-agent/delete.go
  cmd/pbm-agent/oplog.go
  cmd/pbm-agent/restore.go
  cmd/pbm/delete.go
  pbm/backup/backup.go
  pbm/backup/delete.go
  pbm/backup/query.go
  pbm/backup/slicer.go
  pbm/config/config.go
  pbm/oplog/chunk.go
  pbm/slicer/slicer.go
  sdk/impl.go
Labels: bugfix

#908 PBM tests. Set proper user on container re-creation, include pbmLockOp for lock check
  e2e-tests/functions
  e2e-tests/pkg/pbm/clock_skew.go
Labels: maintenance, tests

#909 [PBM-1243] fix heartbeat check for delete-backup --wait
  sdk/impl.go
Labels: bugfix

#910 [PBM-1246] improve delete-pitr command
  cmd/pbm-agent/delete.go
  cmd/pbm/delete.go
  cmd/pbm/main.go
  pbm/oplog/chunk.go
  pbm/oplog/oplogtmp/delete.go
  sdk/sdk.go
  sdk/util.go
Labels: improvement, feature, bugfix

#914 PBM_tests. Fix delete-backup test and disable tests which require fix on PBM side
  e2e-tests/cmd/pbm-test/run.go
  e2e-tests/pkg/tests/sharded/test_backup_cancellation.go
  e2e-tests/pkg/tests/sharded/test_delete_backup.go
Labels: tests
