Repository percona/percona-backup-mongodb, pull requests merged in 2024-08, with the labels that each got.

#954 PBM-1329 Write to temporary file name and sync before renaming
  pbm/storage/fs/fs.go
Labels: community, bugfix

#985 [PBM-341] fix invalid S3 url
  pbm/config/config.go
Labels: bugfix

#990 [PBM-1373] force shutdown on ConflictingOperationInProgress
  pbm/restore/physical.go
Labels: bugfix

#992 change upload part size message for S3
  cmd/pbm/delete.go
  cmd/pbm/status.go
  pbm/backup/physical.go
  pbm/storage/s3/s3.go
  pbm/storage/storage.go
Labels: improvement

#994 [PBM-1344] do not try to copy oplog from physical backup
  pbm/slicer/slicer.go
Labels: bugfix

#997 PBM-1376. Add support for SSE-S3 for S3 providers
  pbm/storage/s3/s3.go
Labels: improvement

#998 [PBM-1378] add Percona Squad notice
  cmd/pbm-agent/main.go
  cmd/pbm-agent/squad.go
Labels: maintenance

#993 Update README.md with Join Percona Squad
  README.md
Labels: maintenance

#996 PBM-1368. PBM version bump
  pbm/version/version.go
Labels: maintenance
